// Generated by Haxe 3.4.0
(function () { "use strict";
var Main = function() {
};
Main.main = function() {
	var value = window.document.getElementById("test");
	var element = (value instanceof HTMLCanvasElement) ? value : null;
	element.onclick = Main.toggleFullscreen;
	Main.fullscreen = new VDSExtern.Fullscreen(element);
};
Main.toggleFullscreen = function(e) {
	if(Main.fullscreen != null) {
		Main.fullscreen.setFullscreen(!Main.fullscreen.getFullscreen());
	}
};
Main.main();
})();

//# sourceMappingURL=test.js.map